-- Promote your account to admin AFTER you have signed up once through the app.
-- Replace the email with the address you registered with, then run this in the
-- Supabase SQL editor.
--
--   update public.profiles
--   set role = 'admin'
--   where id = (select id from auth.users where email = 'you@example.com');
